"""cat

Revision ID: 026b53f9253c
Revises: eb82677c62a3
Create Date: 2019-09-22 18:57:34.775581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '026b53f9253c'
down_revision = 'eb82677c62a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
