"""comments

Revision ID: 1c23a0da73e5
Revises: 6b45307463d7
Create Date: 2019-09-22 11:29:04.038743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c23a0da73e5'
down_revision = '6b45307463d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
