"""username

Revision ID: eb82677c62a3
Revises: 1c23a0da73e5
Create Date: 2019-09-22 14:16:15.532769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb82677c62a3'
down_revision = '1c23a0da73e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('username', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'username')
    # ### end Alembic commands ###
